name: Test Backend

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
    tests:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v7
            
            - name: Setup Python
              uses: actions/setup-python@v5
              with:
                python-version: "3.11"

            - name: Install Dependencies
              run: |
               cd backend
               pip install -r requirements.txt

            - name: Run Pytest
              run: |
                cd backend
                pytest tests/ -v
